### PR TITLE
Add sample configuration file for inclusion in packaging

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by tampakrap** [comment]
Please provide in a comment which are the default values if not specified, or if one specific option is mandatory to be filed

**Comment by smithfarm** [comment]
@tampakrap OK, please look again.

**Comment by tampakrap** [comment]
:+1: (I'll let you merge it, not sure if you are finished)

**Comment by tampakrap** [comment]
post-merge idea: rename the file to .example

**Pull request merged**
