### PR TITLE
dochazka-ldap-batch-create script

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@tampakrap For packaging purposes, we probably don't need to put helper scripts in /usr/bin . . . maybe they could be in /var/lib/dochazka-rest/scripts ?

**Comment by tampakrap** [comment]
Another idea: create -ldap subpackage and put it in /usr/bin normally

**Comment by smithfarm** [comment]
So I should rename the script? To something like "dochazka-ldap-create-employees".

**Comment by smithfarm** [comment]
Or just "dochazka-ldap-create"

**Comment by tampakrap** [comment]
yes, this makes sense

**Comment by smithfarm** [comment]
I wrote the script just as a convenience for testing, but might as well ship it. :-)

**Comment by smithfarm** [comment]
I'll move it to `bin/`

**Comment by tampakrap** [comment]
yes move it to bin/ please, it might be useful for administration issues as well. Eg. we might want a "create-or-retrieve employee" button in the webui in the future, which can call this script

**Comment by smithfarm** [comment]
@tampakrap Already moved it.

**Pull request merged**
